#!/bin/bash

# Details
# https://addons.mozilla.org/en-US/firefox/addon/tabs2clip/

MISSING_REQ=0
for req in mktemp wget unzip zip grep cut date;do
	type $req >/dev/null 2>&1 || { echo >&2 "Missing dependency: $req"; MISSING_REQ=1; }
done

[ $MISSING_REQ -ne 0 ] && { echo "Aborting because of missing dependency"; exit 1; }

# create tmp storage
ZIPFILE=$(mktemp)
EXTRDIR=$(mktemp -d)

# download
wget -q --show-progress 'https://github.com/igorlogius/tabs2clip/archive/master.zip' -O $ZIPFILE

# extract without paths and README
unzip -j $ZIPFILE -d $EXTRDIR -x "*/README"

COMMIT_HASH_SHORT=$(wget --header="Accept: application/vnd.github.VERSION.sha" -qO- http://api.github.com/repos/igorlogius/tabs2clip/commits/master | cut -c1-7)

MAJOR_VERSION=$(grep '"version"' $EXTRDIR/manifest.json |cut -d'"' -f4);

NEW_VERSION="${MAJOR_VERSION}${COMMIT_HASH_SHORT}";

# insert commit hash into manifest 
sed -i "s/\"version\".*/\"version\": \"${NEW_VERSION}\",/" $EXTRDIR/manifest.json

# re-pack as xpi (zip) without paths and extended file attributes 
XPI="tabs2clip-${NEW_VERSION}-$(date '+%F_%T').xpi"
zip -X -j $XPI $EXTRDIR/*

# remove tmp storage
rm -f $EXTRDIR/* && rmdir $EXTRDIR/

# show conent of xpi
unzip -l $XPI

